backend:
  name: github
  repo: ssowerby/hypnotherapy-site
  branch: master
  
media_folder: "static/uploads"
public_folder: "/uploads"
collections:

  - name: "service"
    label: "Service"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "order", widget: "number", valueType: "int", min: 1, max: 100 }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Publish Date", name: "publishDate", widget: "datetime", format: "YYYY-MM-DD HH:mm:ss"}
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "faq"
    label: "FAQ"
    folder: "content/faqs"
    create: true
    slug: "{{slug}}"
    fields:
    - { label: "Question", name: "title", widget: "string" }
    - { label: "Answer", name: "body", widget: "markdown" }

  - name: "section"
    label: "Section"
    folder: "content/sections"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "page"
    label: "Page"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
